apiVersion: skaffold/v3alpha1
kind: Config

metadata:
  name: ticketing

manifests:
  rawYaml:
    - ./infra/k8s/*

build:
  # local:
  #   push: false
  googleCloudBuild:
    concurrency: 1
    projectId: snappy-provider-368019
  
  artifacts:
    - image: gcr.io/snappy-provider-368019/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

deploy:
  kubectl: {}
    