apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
    - image: bugalala/client
      context: client
      sync:
        manual:
          - src: src/**/*.tsx
            dest: .
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: bugalala/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
